apiVersion: v1
kind: Secret
metadata:
  name: mautic-db-secret
  namespace: mautic
type: Opaque
data:
  mysql-root-password: cm9vdF9wYXNzd29yZA== # Base64-encoded 'root_password'
  mysql-user-password: bWF1dGljX3Bhc3N3b3Jk # Base64-encoded 'mautic_password'
